### ISSUE TITLE
Updating of the Introduction Section.

### ISSUE THREAD

**Issue by mhnusbaum** [IHE/ITI.sIPS#16]
I've taken the liberty of re-drafting the introduction section to the sIPS profile, to better accommodate how this profile might be marketed to the implementation community.  The changes reflect a few important considerations:

- how sIPS fits together with PCC-IPS
- referencing sIPS as a "profile" rather than an "implementation guide".  This eliminates confusion over the HL7 publications, which they call "implementation guides" rather than "specifications".  Specifications are seen to be the purview of ISO27269.
- I've indicated that the "sIPS profile provides implementation guidance", which it does!!
- I've made this slightly less technical than before, although most of the previous intro text and references have been retained.
- I've provided clarity on where sIPS stands in relation to the HL7 CDA IG (which has had no uptake, but folks continue to see potential)... HL7 is not prepared to deprecate the CDA IG just yet.
- I've tried to position sIPS as a means to address many existing XDS infrastructures, such as those in Europe, Sequoia in the US, Canada's "reference architecture" supporting PS-CA, etc.

I hope my suggestions are understood, and eventually find their way into the final published version.  Please reach out if you need to get further clarity or background.  Mike.

My proposed re-draft is as follows:

The Sharing of IPS (sIPS) IHE Profile has been created to facilitate the exchange of the International Patient Summary (IPS) content, as defined in the [ISO 27269](https://www.iso.org/standard/79491.html) data model specification, utilizing IHE’s [XDS document sharing infrastructure](https://profiles.ihe.net/ITI/HIE-Whitepaper/index.html) both “locally” and “cross-community”.  It has been designed specifically to remove barriers to adoption, by leveraging architectures that are currently implemented, well-established, and robust.  The sIPS Profile provides implementation guidance to vendors and implementers, and joins a growing “suite” of [IPS standards](https://international-patient-summary.net/) artefacts contributed by a variety of Standards Development Organizations (SDOs), and coordinated by the [Joint Initiative Council for Global Health Informatics Standardization (JIC)](http://jointinitiativecouncil.org/).

An IPS document is an electronic health record extract, taken at a point in time, containing essential healthcare information about a subject of care. It is designed for supporting the use case scenario for ‘planned and unplanned, cross border care’, and although it is intended to be used across international borders, it is equally useful to exchange information across any jurisdictional border, including those within a particular region or country. The IPS dataset is minimal and non-exhaustive; specialty-agnostic and condition-independent but still clinically relevant.

This profile leverages [IHE IPS content profile](https://wiki.ihe.net/index.php/International_Patient_Summary_(IPS)), the most recent version published in 2023, which in turn references HL7s IPS Implementation Guides (IGs) for [FHIR](http://hl7.org/fhir/uv/ips) (2022) and [CDA](https://www.hl7.org/implement/standards/product_brief.cfm?product_id=483) (2018). Due to the minimal global uptake of the CDA encoding of the IPS at this time, the focus of the sIPS Profile is currently based on the specification provided in the [HL7 FHIR IG](http://hl7.org/fhir/uv/ips).  As such, the sIPS Profile does not further refine the IPS, thus any document conforming to the [HL7 base IPS specification](http://hl7.org/fhir/uv/ips) is applicable here.  The IPS specification is composed of a set of robust, well-defined and potentially reusable sets of core data items (indicated as the IPS library in the figure below).

The sIPS Profile provides guidance to implementers on how a number of important functions may be leveraged to support key IPS use cases.  These include:

•	Publishing an IPS
•	On Demand Access to an IPS
•	Retrieving an IPS
•	Pushing an IPS to a Recipient

As noted, the IHE sIPS Profile does not modify the [HL7 IPS](http://hl7.org/fhir/uv/ips) FHIR specification, but rather provides for methods of sharing the IPS using [IHE Document Sharing](https://profiles.ihe.net/ITI/HIE-Whitepaper/index.html). The IPS, as a “current summary”, is an excellent document for the [“On-Demand” capability of the Document Sharing](https://profiles.ihe.net/ITI/HIE-Whitepaper/index.html#212-dynamic-documents) infrastructure. On-Demand is available in [XDS](https://profiles.ihe.net/ITI/TF/Volume1/ch-10.html#10) with [On-Demand Documents Option](https://profiles.ihe.net/ITI/TF/Volume1/ch-10.html), [XCA](https://profiles.ihe.net/ITI/TF/Volume1/ch-18.html) with [On-Demand Documents Option](https://profiles.ihe.net/ITI/TF/Volume1/ch-18.html#18.2.4), and with [MHD/MHDS](https://profiles.ihe.net/ITI/MHD/index.html). Further details for IPS use of On-Demand are outlined below in section 3.9.2.1.2. IHE Document Sharing also has “Stable” and “Delayed Assembly” document entry types that are further explained in the [HIE Whitepaper: Dynamics Documents](https://profiles.ihe.net/ITI/HIE-Whitepaper/index.html#212-dynamic-documents).

**Comment by JohnMoehrke** [comment]
committee review:

* generally agree with a few modifications
* The first sentence of the last paragraph should appear at the top as it is the key deliverable of sIPS -- reworded for more active voice.
  * The Sharing of IPS (sIPS) IHE Profile provides for methods of sharing the IPS using [IHE Document Sharing](https://profiles.ihe.net/ITI/HIE-Whitepaper/index.html) but does not modify the [HL7 IPS](http://hl7.org/fhir/uv/ips) FHIR specification.
* do not mention the PCC-IPS as we have agreement with PCC committee that they will extract out their option "FHIR Occupational Data for Health" as a new supplement, and the existing PCC-IPS will be retired as otherwise replaced by sIPS. We will not mention this in the text as mentioning it will present revision complexity.
* given that IHE has a [long standing position that an IHE-Profile is an implementation guide](https://profiles.ihe.net/GeneralIntro/ch-3.html), we do not agree to downplay that this is an implementation guide.   Do agree to start the section with the use of IHE-Profile.
