### ISSUE TITLE
[Bug]: Can a Content Creator/Content Consumer satisfy sIPS by supporting $summary as the only exchange mechanism?

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.sIPS#22]
### Contact Details

slagesse@epic.com

### Section Number

1:56.1.1.1

### What is wrong

In section 1:56.1.1.1, the requirements on the Content Creator are:

"The [Content Creator](https://profiles.ihe.net/ITI/sIPS/pcc.html#31-document-sharing-pcc-1) creates the [IPS content](http://hl7.org/fhir/uv/ips) and shares it using one of the methods defined in the [IHE Document Sharing Health Information Exchange](https://profiles.ihe.net/ITI/HIE-Whitepaper/index.html)."

Similarly, the requirements on the Content Consumer are:

"The [Content Consumer](https://profiles.ihe.net/ITI/sIPS/pcc.html#31-document-sharing-pcc-1) consumes the [IPS content](http://hl7.org/fhir/uv/ips) and obtains it using one of the methods defined in the [IHE Document Sharing Health Information Exchange](https://profiles.ihe.net/ITI/HIE-Whitepaper/index.html)."

But in section 3:5.9.2.1.2, we say:

"When the On-Demand entry is requested by a Document Consumer, the responding actor may chose to utilize the [IPS $summary operation](http://hl7.org/fhir/uv/ips/OperationDefinition-summary.html). This use of the [$summary operation](http://hl7.org/fhir/uv/ips/OperationDefinition-summary.html) is not required to be the method used."

So, volume 3 suggests one can use $summary to exchange IPS. But, there is no IHE profile that defines $summary. So, based on the Volume 1 text, is is unclear whether a Content Creator/Consumer that supports exchanging of IPS using $summary, but does not support exchanging it via any IHE document sharing profiles, would be conformant to sIPS. 

### Describe the solution you'd like

Clarify whether this is allow. IMO, $summary is a very straightforward way to exchange IPS and should be a mechanism to satisfy sIPS. 

### Priority

{"High"=>"Important issue where there is major issue to be resolved. Requires discussion and debate."}

### Code of Conduct

- [X] I agree to follow the IHE Code of Conduct

**Comment by JohnMoehrke** [comment]
If you are communicating a DocumentReference as indicated as an On-Demand entry (as in supporting the MHD Document Source, Document Consumer) then yes.  The quoted text about $summary is expressing that the URL in the DocumentReference, when retrieved is satisfied by the $summary operation. The Document Consumer does not use $summary (at least they don't know they are in the case where the URL is a GET on $summary).

But without the DocumentReference, this is not an IHE profiled method. It certainly is a method, just not one that IHE has profiled.
